# .streamlit/secrets.toml

[mongo]
# رشته اتصال به پایگاه داده MongoDB Atlas
uri = "mongodb+srv://db-Jasrvis:8yJJ_-Vx2K3i_M7@jarvis.n91ewxb.mongodb.net/?retryWrites=true&w=majority&appName=Jarvis"

[google_ai]
# کلید API خود را از Google AI Studio دریافت کنید
api_key = "AIzaSyDns3BHOFwG98hEIiKbm2GMWhv9a66Bgq4"
