[run]
# اسم فایل اصلی که Chainlit اجرا می‌کنه
module_name = "app"

# حالت توسعه (true باشه راحت تر تست می‌کنیم)
dev = true

# پورت دلخواه (Render خودش PORT رو ست می‌کنه)
port = 8000

[tools]
# هیچ ابزاری فعال نیست → لاگ اضافی کاهش پیدا می‌کنه
enable = []
